**1. Load CSV**  
Read trades.csv using pandas

In [2]:
#A-1: Load CSV
import pandas as pd
df= pd.read_csv("trade_log.csv")
df

             timestamp      Symbol  Buy_Price  Sell_Price  Qty
0  2026-04-25 23:28:34       Nifty    25000.0     25500.0   10
1  2026-04-25 23:29:06  Bank Nifty    59000.0     58700.0   10
2  2026-04-25 23:29:19      Sensex    80000.0     80500.0   10

**2. Analyze Data**  
Print:  
first 5 rows  
summary stats

In [ ]:
#A-2: Analyzing data
df.head()
df.describe()

          Buy_Price    Sell_Price   Qty
count      3.000000      3.000000   3.0
mean   54666.666667  54900.000000  10.0
std    27754.879451  27696.209127   0.0
min    25000.000000  25500.000000  10.0
25%    42000.000000  42100.000000  10.0
50%    59000.000000  58700.000000  10.0
75%    69500.000000  69600.000000  10.0
max    80000.000000  80500.000000  10.0

**3. PnL Calculator**  
entry,exit  
100,110  
200,190  

👉 Add column pnl  
👉 Compute total PnL

In [ ]:
#A-3: PnL Calculator
df["PnL"]=(df["Sell_Price"]-df["Buy_Price"])*df["Qty"]
total_PnL=df["PnL"].sum()
print(df)
print("\nTotal PnL:",total_PnL)

             timestamp      Symbol  Buy_Price  Sell_Price  Qty     PnL
0  2026-04-25 23:28:34       Nifty    25000.0     25500.0   10  5000.0
1  2026-04-25 23:29:06  Bank Nifty    59000.0     58700.0   10 -3000.0
2  2026-04-25 23:29:19      Sensex    80000.0     80500.0   10  5000.0

Total PnL: 7000.0

**4. Filter Data**  
Show trades where profit > 0

In [ ]:
#A-4: Filter Data
Profit_trades=df[df["PnL"]>0]
print(Profit_trades)

             timestamp  Symbol  Buy_Price  Sell_Price  Qty     PnL
0  2026-04-25 23:28:34   Nifty    25000.0     25500.0   10  5000.0
2  2026-04-25 23:29:19  Sensex    80000.0     80500.0   10  5000.0

**5. Save New File**  
Save updated data to new CSV  
df.to_csv("output.csv", index=False)

In [ ]:
#A-5: Save to CSV 
df.to_csv("Output.csv", index=False)